---
- name: Create service directory
  file:
    path: "{{ service_path }}"
    state: directory

- name: Create data directory
  file:
    path: "{{ data_path }}"
    state: directory
    mode: 0777

- name: Spin up the container
  docker_container:
    name: "{{ service_name }}"
    image: nodered/node-red:3.1.9-18-minimal
    ports:
      - "127.0.0.1:1880:1880"
    volumes:
      - "{{ data_path }}:/data"
    networks:
      - name: "{{ iot_network }}"
