---
- name: Create data directory
  file:
    path: "{{ data_path }}"
    state: directory
    recurse: yes

- name: Upload configuration
  copy:
    src: "{{ item }}"
    dest: "{{ data_path }}/{{ item | basename }}"
    mode: 0644
    force: false
  with_fileglob:
    - "*.json"

# If it does not exist, it means that Homebridge has never been started.
- name: Check if package.json exists
  stat:
    path: "{{ data_path }}/package.json"
  register: package_json

- name: Spin up the container
  docker_container:
    name: "{{ service_name }}"
    image: homebridge/homebridge:2024-05-02
    env:
      PGID: "1000"
      PUID: "1000"
      HOMEBRIDGE_CONFIG_UI: "1"
    volumes:
      - "{{ data_path }}:/homebridge"
    # Because it's necessary to be on the same subnet as the HomeKit controller.
    # (it's an mDNS thing, I guess)
    network_mode: host
    restart_policy: unless-stopped

- name: Install z2m plugin # at the first run
  command: "docker exec {{ service_name }} /bin/bash -c 'hb-service add homebridge-z2m'"
  when: package_json.stat.exists == False