---
- hosts: all
  vars:
    iot_home: "/home/{{ ansible_user }}"
    iot_network: iot
    iot_services_path: "{{ iot_home }}/services"
  module_defaults:
    apt:
      update_cache: yes
      cache_valid_time: 300
  roles:
    - role: sys/ssh
      when: public_key is defined
      tags: [sys, ssh]

    - role: sys/common
      tags: [sys, common]

    - role: sys/ntp
      tags: [sys, ntp]

    - role: sys/locale
      tags: [sys, locale]

    - role: sys/docker
      tags: [sys, docker]

    - role: app/mosquitto
      tags: [app, mosquitto]

    - role: app/zigbee2mqtt
      tags: [app, zigbee2mqtt]

    - role: app/homebridge
      tags: [app, homebridge]

    - role: app/nodered
      tags: [app, nodered]

    - role: app/gateway
      tags: [app, gateway]
