---
- hosts: all
  vars:
    iot_home: /opt/iot
    iot_network: iot
  module_defaults:
    apt:
      update_cache: yes
      cache_valid_time: 300
    docker_container:
      log_driver: json-file
      log_options:
        max-size: 10m
        max-file: "3"
      restart_policy: unless-stopped
  roles:
    - role: sys/ssh
      when: ssh_pubkey is defined
      tags: [sys, ssh]

    - role: sys/common
      tags: [sys, common]

    - role: sys/ntp
      tags: [sys, ntp]

    - role: sys/locale
      tags: [sys, locale]

    - role: sys/docker
      tags: [sys, docker]

    - role: app/mosquitto
      tags: [app, mosquitto]

    - role: app/zigbee2mqtt
      tags: [app, zigbee2mqtt]

    - role: app/homebridge
      tags: [app, homebridge]

    - role: app/nodered
      tags: [app, nodered]

    - role: app/telegraf
      tags: [app, telegraf]

    - role: app/dashboard
      tags: [app, dashboard]
