---
- hosts: all
  vars:
    iot_home: /home/vagrant
  module_defaults:
    apt:
      update_cache: yes
      cache_valid_time: 300
  roles:
    - common
    - docker
    - mosquitto
    - zigbee2mqtt
    - homebridge
    - gateway
