---
- hosts: all
  vars:
    iot_home: "/home/{{ ansible_user }}"
  module_defaults:
    apt:
      update_cache: yes
      cache_valid_time: 300
  roles:
    - sys/common
    - sys/locale
    - sys/docker
    - app/mosquitto
    - app/zigbee2mqtt
    - app/homebridge
    - app/nodered
    - app/gateway
