---
- name: Set timezone
  timezone:
    name: Europe/Budapest

# We don't need IPv6 on the local network, so turn it off.
- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: "1"
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Upgrade the operating system
  apt:
    upgrade: safe

- name: Install some useful tools
  apt:
    name:
      - dnsutils
      - net-tools