---
- name: Create data directory
  file:
    path: "{{ service_path }}/data"
    state: directory
    recurse: yes

- name: Upload configuration
  copy:
    src: configuration.yaml
    dest: "{{ service_path }}/configuration.yaml"
    mode: 0644

- name: Generate PAN ID
  template:
    src: pan_id.yaml.j2
    dest: "{{ service_path }}/pan_id.yaml"
    mode: 0644
    force: no # Do not overwrite if already exists.

- name: Generate network key
  template:
    src: network_key.yaml.j2
    dest: "{{ service_path }}/network_key.yaml"
    mode: 0644
    force: no # Do not overwrite if already exists.

- name: Detect zigbee device
  command: set -o pipefail && ls -1 /dev/serial/by-id/* | head -n1
  register: zigbee_device

- name: Spin up the container
  docker_container:
    name: "{{ service_name }}"
    image: koenkk/zigbee2mqtt:1.33.1
    volumes:
      - "{{ service_path }}/data:/app/data"
      - "{{ service_path }}/configuration.yaml:/app/configuration.yaml:ro"
      - "{{ service_path }}/pan_id.yaml:/app/pan_id.yaml:ro"
      - "{{ service_path }}/network_key.yaml:/app/network_key.yaml:ro"
    networks:
      - name: iot
    devices:
      - "{{ zigbee_device.stdout }}:/dev/ttyACM0"
    restart_policy: unless-stopped
