---
- name: Create data directory
  file:
    path: "{{ data_path }}"
    state: directory
    recurse: yes

- name: Upload configuration
  copy:
    src: configuration.yaml
    dest: "{{ data_path }}/configuration.yaml"
    mode: 0644

- name: Detect zigbee device
  shell: set -o pipefail && ls -1 /dev/serial/by-id/* | head -n1
  args:
    executable: /bin/bash
  register: zigbee_device

- name: Spin up the container
  docker_container:
    name: "{{ service_name }}"
    image: koenkk/zigbee2mqtt:1.34.0
    env:
      ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ zigbee_pan_id }}"
      ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ zigbee_network_key | string }}"
    volumes:
      - "{{ service_path }}/data:/app/data"
    networks:
      - name: "{{ iot_network }}"
    ports:
      - '8080:8080'
    devices:
      - "{{ zigbee_device.stdout }}:/dev/ttyACM0"
    restart_policy: unless-stopped
