---
- name: Create configuration directory
  file:
    path: "{{ service_path }}"
    state: directory
    recurse: yes

- name: Upload configuration
  copy:
    src: mosquitto.conf
    dest: "{{ service_path }}/mosquitto.conf"
    mode: 0644

- name: Spin up the container
  docker_container:
    name: "{{ service_name }}"
    image: eclipse-mosquitto:2.0.18
    volumes:
      - "{{ service_path }}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
    networks:
      - name: "{{ iot_network }}"
    ports:
      - '127.0.0.1:1883:1883'
