---
- name: Create the configuration directory
  file:
    path: "{{ iot_home }}/services/{{ service_name }}/conf.d"
    state: directory
    recurse: yes

- name: Upload configurations
  copy:
    src: "{{ item }}"
    dest: "{{ iot_home }}/services/{{ service_name }}/conf.d/{{ item | basename }}"
    mode: 0644
  with_fileglob:
    - conf.d/*.conf
  notify:
    - reload nginx

- name: Upload auth token config
  template:
    src: auth_token.conf.j2
    dest: "{{ iot_home }}/services/{{ service_name }}/conf.d/00_auth_token.conf"
    mode: 0644
    force: no
  notify:
    - reload nginx

- name: Upload HTML files
  copy:
    src: html
    dest: "{{ iot_home }}/services/{{ service_name }}"

- name: Install python3-passlib for the htpasswd module
  apt:
    name: python3-passlib

- name: Generate htpasswd
  htpasswd:
    path: "{{ iot_home }}/services/{{ service_name }}/htpasswd"
    name: admin
    password: trallala
    owner: root
    group: 101 # nginx user in the container
    mode: 0640

- name: Spin up the nginx container
  docker_container:
    name: "{{ service_name }}"
    image: nginx:latest
    volumes:
      - "{{ iot_home }}/services/{{ service_name }}/conf.d:/etc/nginx/conf.d:ro"
      - "{{ iot_home }}/services/{{ service_name }}/htpasswd:/etc/nginx/htpasswd:ro"
      - "{{ iot_home }}/services/{{ service_name }}/html:/usr/share/nginx/html:ro"
    capabilities:
      - CAP_NET_BIND_SERVICE
    network_mode: host
    restart_policy: unless-stopped
