---
- name: Create data directory
  file:
    path: "{{ iot_home }}/services/{{ ansible_role_name }}/data"
    state: directory
    recurse: yes

- name: Upload configuration
  copy:
    src: "{{ item }}"
    dest: "{{ iot_home }}/services/{{ ansible_role_name }}/{{ item | basename }}"
    mode: 0644
  with_fileglob:
    - "*.json"

# If it does not exist, it means that Homebridge has never been started.
- name: Check if package.json exists
  stat:
    path: "{{ iot_home }}/services/{{ ansible_role_name }}/data/package.json"
  register: package_json

- name: Spin up the container
  docker_container:
    name: "{{ ansible_role_name }}"
    image: oznu/homebridge:2023-01-08
    env:
      PGID: "1000"
      PUID: "1000"
      HOMEBRIDGE_CONFIG_UI: "1"
    volumes:
      - "{{ iot_home }}/services/{{ ansible_role_name }}/data:/homebridge"
    # Because it's necessary to be on the same subnet as the HomeKit controller.
    # (it's an mDNS thing, I guess)
    network_mode: host
    restart_policy: unless-stopped

- name: Install z2m plugin # at the first run
  command: "docker exec {{ ansible_role_name }} /bin/bash -c 'hb-service add homebridge-z2m'"
  when: package_json.stat.exists == False