---
all:
  hosts:
    rpi:
      ansible_host: "{{ ssh_host }}"
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: "{{ ssh_username }}"
      ansible_become: true
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o PreferredAuthentications=password,publickey"
      ansible_ssh_pass: "{{ ssh_password }}"

      dashboard_username: "{{ lookup('env', 'DASHBOARD_USERNAME') }}"
      dashboard_password: "{{ lookup('env', 'DASHBOARD_PASSWORD') }}"

      zigbee_pan_id: "{{ lookup('env', 'ZIGBEE_PAN_ID') }}"
      zigbee_network_key: "{{ lookup('env', 'ZIGBEE_NETWORK_KEY') }}"

      grafana_url: "{{ lookup('env', 'GRAFANA_URL') }}"
      grafana_username: "{{ lookup('env', 'GRAFANA_USERNAME') }}"
      grafana_password: "{{ lookup('env', 'GRAFANA_PASSWORD') }}"