---
- name: Create configuration directory
  file:
    path: "{{ iot_home }}/services/{{ ansible_role_name }}"
    state: directory
    recurse: yes

- name: Upload configuration
  copy:
    src: mosquitto.conf
    dest: "{{ iot_home }}/services/{{ ansible_role_name }}/mosquitto.conf"
    mode: 0644

- name: Spin up the container
  docker_container:
    name: "{{ ansible_role_name }}"
    image: eclipse-mosquitto:2.0.18
    volumes:
      - "{{ iot_home }}/services/{{ ansible_role_name }}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
    networks:
      - name: iot
    ports:
      - '127.0.0.1:1883:1883'
    restart_policy: unless-stopped
