---
- name: Install Docker
  apt:
    name:
      - docker.io
      - python3-docker

- name: Add IoT user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create IoT network
  docker_network:
    name: "{{ iot_network }}"