---
- name: Install prerequisites for Docker repository
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']

- name: Add Docker APT repo signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker CE
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Install pip
  apt:
    name: ['pip', 'virtualenv']

- name: Install Python libraries required by the docker module
  pip:
    name: docker

- name: Add IoT user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create IoT network
  docker_network:
    name: "{{ iot_network }}"
