---
- name: Install Docker
  apt:
    name:
      - docker.io
      - python3-docker

- name: Add IoT user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create IoT network
  docker_network:
    name: "{{ iot_network }}"

- name: Inspect the IoT network
  docker_network_info:
    name: "{{ iot_network }}"
  register: iot_network_info

- name: Register the IP address of gateway
  set_fact:
    docker_host_ip: "{{ iot_network_info.network.IPAM.Config[0].Gateway }}"
